// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/skills": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/skills";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/skills.tsx": {
    id: "routes/skills";
    page: "/skills";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/skills": typeof import("./app/routes/skills.tsx");
};